"""baseline: existing schema

Revision ID: 28028c6fc495
Revises: 
Create Date: 2026-08-27 17:52:18.313933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28028c6fc495'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_exercises_id'), 'exercises', ['id'], unique=False)
    op.drop_constraint(op.f('foods_fdc_id_key'), 'foods', type_='unique')
    op.create_index(op.f('ix_foods_fdc_id'), 'foods', ['fdc_id'], unique=True)
    op.create_index(op.f('ix_foods_id'), 'foods', ['id'], unique=False)
    op.create_index(op.f('ix_nutrition_logs_id'), 'nutrition_logs', ['id'], unique=False)
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.drop_constraint(op.f('workout_sets_workout_id_fkey'), 'workout_sets', type_='foreignkey')
    op.create_foreign_key(None, 'workout_sets', 'user_workouts', ['workout_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workout_sets', type_='foreignkey')
    op.create_foreign_key(op.f('workout_sets_workout_id_fkey'), 'workout_sets', 'user_workouts', ['workout_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_index(op.f('ix_nutrition_logs_id'), table_name='nutrition_logs')
    op.drop_index(op.f('ix_foods_id'), table_name='foods')
    op.drop_index(op.f('ix_foods_fdc_id'), table_name='foods')
    op.create_unique_constraint(op.f('foods_fdc_id_key'), 'foods', ['fdc_id'])
    op.drop_index(op.f('ix_exercises_id'), table_name='exercises')
    # ### end Alembic commands ###
