"""add user_favorite_foods table

Revision ID: 9c4a1b7fe210
Revises: 73ef2c09548a
Create Date: 2026-09-07 14:05:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '9c4a1b7fe210'
down_revision: Union[str, Sequence[str], None] = '73ef2c09548a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Hand-written rather than autogenerated, for the same reason
    e3f1f4840e5f was trimmed by hand: autogenerate proposes unrelated
    drift alongside the change you actually want. This creates only
    user_favorite_foods.

    Structure is a deliberate mirror of user_favorite_exercises - a
    per-user join table rather than a flag on foods, because foods is
    shared (user_id IS NULL rows are the USDA reference set) and a column
    there would leak one user's favourites to everyone.
    """
    op.create_table(
        'user_favorite_foods',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('food_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'food_id', name='uq_user_favorite_foods_user_food'),
    )
    op.create_index(op.f('ix_user_favorite_foods_id'), 'user_favorite_foods', ['id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_user_favorite_foods_id'), table_name='user_favorite_foods')
    op.drop_table('user_favorite_foods')
