"""add coach_conversations and coach_messages tables

Revision ID: b4d21c0a7e15
Revises: 9c4a1b7fe210
Create Date: 2026-09-09 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b4d21c0a7e15'
down_revision: Union[str, Sequence[str], None] = '9c4a1b7fe210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Hand-written rather than autogenerated, matching the convention of the
    preceding migrations: autogenerate proposes unrelated drift alongside
    the change actually wanted. This creates only the two Coach tables.

    Both cascade from their parent, so deleting a conversation takes its
    messages with it and a future account deletion takes both. That is a
    deliberate departure from the older tables' deferred cascade decision:
    these rows are conversation scratch data with no reporting value once
    the thread is gone.
    """
    op.create_table(
        'coach_conversations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_coach_conversations_id'), 'coach_conversations', ['id'])
    op.create_index(op.f('ix_coach_conversations_user_id'), 'coach_conversations', ['user_id'])

    op.create_table(
        'coach_messages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('conversation_id', sa.Integer(), nullable=False),
        sa.Column('role', sa.Text(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['conversation_id'], ['coach_conversations.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_coach_messages_id'), 'coach_messages', ['id'])
    op.create_index(op.f('ix_coach_messages_conversation_id'), 'coach_messages', ['conversation_id'])


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_coach_messages_conversation_id'), table_name='coach_messages')
    op.drop_index(op.f('ix_coach_messages_id'), table_name='coach_messages')
    op.drop_table('coach_messages')
    op.drop_index(op.f('ix_coach_conversations_user_id'), table_name='coach_conversations')
    op.drop_index(op.f('ix_coach_conversations_id'), table_name='coach_conversations')
    op.drop_table('coach_conversations')
