"""add photo_filename to nutrition_logs and progress_photos table

Revision ID: c8f3a9d2e6b1
Revises: b4d21c0a7e15
Create Date: 2026-09-09 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c8f3a9d2e6b1'
down_revision: Union[str, Sequence[str], None] = 'b4d21c0a7e15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Hand-written rather than autogenerated, matching the convention of the
    preceding migrations. Adds only the basic-upload photo storage: a
    nullable filename column on the existing nutrition_logs table (a log
    can be created with or without a photo, and most won't have one), and
    a new progress_photos table, cascading from its user the same way
    coach_conversations does - these are standalone uploads with no
    reporting value once the account or the row itself is gone.
    """
    op.add_column(
        'nutrition_logs',
        sa.Column('photo_filename', sa.Text(), nullable=True),
    )

    op.create_table(
        'progress_photos',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('photo_filename', sa.Text(), nullable=False),
        sa.Column('taken_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_progress_photos_id'), 'progress_photos', ['id'])
    op.create_index(op.f('ix_progress_photos_user_id'), 'progress_photos', ['user_id'])


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_progress_photos_user_id'), table_name='progress_photos')
    op.drop_index(op.f('ix_progress_photos_id'), table_name='progress_photos')
    op.drop_table('progress_photos')
    op.drop_column('nutrition_logs', 'photo_filename')
