"""add created_at to workout_sets, nutrition_logs, body_weight_logs

Revision ID: d3a7c1f9b264
Revises: c8f3a9d2e6b1
Create Date: 2026-09-11 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd3a7c1f9b264'
down_revision: Union[str, Sequence[str], None] = 'c8f3a9d2e6b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Hand-written rather than autogenerated, matching the convention of the
    preceding migrations. Adds one nullable, server-defaulted column to
    each of three tables - purely additive, no existing column changes, no
    backfill needed (existing rows get NULL, which the idempotency checks
    treat the same as "no recent duplicate found").

    None of the three columns are exposed through the API; they exist only
    so their routes can tell a same-request retry (a duplicate submitted a
    few seconds after the first) apart from a later, genuinely separate
    submission with coincidentally the same values. See the model comments
    in app/models.py and the routes in app/routes/ for why logged_at could
    not be reused for this on nutrition_logs/body_weight_logs, and why
    workout_sets had no timestamp column to reuse at all.
    """
    op.add_column(
        'workout_sets',
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    )
    op.add_column(
        'nutrition_logs',
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    )
    op.add_column(
        'body_weight_logs',
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('body_weight_logs', 'created_at')
    op.drop_column('nutrition_logs', 'created_at')
    op.drop_column('workout_sets', 'created_at')
